### ISSUE TITLE
there's a long delay after depositing/withdrawing tokens to a strat vault before it shows up in the balance

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.webapp#113]

**Comment by hardingjam** [comment]
We could add a "waiting for subgraph" step, similar to the SFT repo?

**Comment by thedavidmeister** [comment]
it's taking like 5 minutes for me today, that's too long for a modal

**Comment by hardyjosh** [comment]
@findolor i think we can trigger a refetch when withdraw/deposit is confirmed, same as the we did for the app
