### ISSUE TITLE
webapp shows wrong pairs in the quote table

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.webapp#114]
![IMAGE 2024-10-08 12:20:30](https://github.com/user-attachments/assets/e719daaa-a172-4bd4-80cd-8b4fc2f255c9)

this typically happens when using the subgraph fields after deserialization (unordered) rather than going to the actual order data

@rouzwelt has more information if needed

**Comment by findolor** [comment]
Waiting for https://github.com/rainlanguage/rain.orderbook/pull/957 to be merged to continue on this PR
