### ISSUE TITLE
trying to deposit when there's no allowance

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.webapp#208]
sometimes it skips straight to depsit when there's no allowance for the token

**Comment by hardingjam** [comment]
I'm not able to reproduce this issue, do you remember what strategy/network it happened on?

**Comment by hardingjam** [comment]
Possibly fixed by #138

**Comment by thedavidmeister** [comment]
ok, i haven't seen this issue in a while so i'm ok to close it and reopen if needed
