### ISSUE TITLE
descriptions don't respect paragraphs

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.webapp#30]
<img width="684" alt="Screenshot 2024-09-28 at 20 06 57" src="https://github.com/user-attachments/assets/5a793d2f-9a43-4c3a-8ef0-d223c49d0413">
<img width="737" alt="Screenshot 2024-09-28 at 20 07 34" src="https://github.com/user-attachments/assets/7aaf10f2-1bf2-4f77-9e0f-2604e7371d99">

single para and double para doesn't make a difference, always get inline text, not even a line break

<img width="1201" alt="Screenshot 2024-09-28 at 20 07 24" src="https://github.com/user-attachments/assets/ed1681b5-7c39-491e-be7c-5f849bc0b809">

**Comment by hardingjam** [comment]
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/d41d7392-e930-49cc-ba93-7235069dd892">
