### ISSUE TITLE
rabby error 413

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.webapp#313]
<img width="400" alt="Screenshot 2024-12-08 at 11 42 36" src="https://github.com/user-attachments/assets/232acecc-86c0-4d09-a6fe-29a11cd8005c">

rabby showing 413 error when trying to deploy https://tinyurl.com/27mjafvh

**Comment by thedavidmeister** [comment]
i'm getting no error, but greyed out "confirm" on MM without any message

rainbow wallet works for me

seeing same error on ETH/USDC dca on arbitrume

NOT seeing error on canary deploys

**Comment by Yuslv12** [comment]
Hello @thedavidmeister  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by thedavidmeister** [comment]
ok so @hardyjosh this just randomly fixed itself, i have no idea what the problem was
