### ISSUE TITLE
raindex says "strategy is live" even if it reverts during deploy

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.webapp#62]
really easy way to get it to revert is to set the deposit as 0 so the multicall fails

app will still say "strat is live" even though the txn reverts

**Comment by thedavidmeister** [comment]
<img width="502" alt="Screenshot 2024-10-01 at 18 24 10" src="https://github.com/user-attachments/assets/f0521af4-2ee0-43d9-bb28-305f28e8e64c">

<img width="568" alt="Screenshot 2024-10-01 at 18 24 30" src="https://github.com/user-attachments/assets/e8f60abb-f8ec-48ab-8373-a1fbe146c988">

clicking the track button just goes to an empty strats page

**Comment by hardingjam** [comment]
Which strategy did you use here? I'm able to deploy a strategy with 0 deposit 

<img width="640" alt="image" src="https://github.com/user-attachments/assets/0bbf336f-f5f4-4be0-8640-f970f7690534">

**Comment by hardyjosh** [comment]
@hardingjam main thing is we handle the error case properly - you could force an error by forcing zero deposit locally, see what comes back and then use that error in a test?
