### ISSUE TITLE
there's no indication of network on the strategy page

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.webapp#84]
it's weird that the active network doesn't display anywhere on the strategy
so like, if i have rabby open and set to eth network, but my strat is on arbitrum
and i go to deposit, it just says "no balance"
but nowhere on the strat does it say that i need to be on arbitrum
and the strat knows it is on arbitrum, but it gives me the ethereum balance
i have to manually swap over to arb on rabby then deposit, and then it shows the right balance

**Comment by hardyjosh** [comment]
This has been resolved
